# Generated by Django 2.2.28 on 2024-10-06 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
        ('api', '0006_auto_20241006_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('lateral', models.CharField(blank=True, max_length=3, null=True)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('hostel', models.CharField(blank=True, max_length=3, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('transport', models.CharField(blank=True, max_length=3, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('last_exam_passed', models.CharField(blank=True, max_length=100, null=True)),
                ('board', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year_passing', models.IntegerField(blank=True, null=True)),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('marks_secured', models.IntegerField(blank=True, null=True)),
                ('cgpa_or_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('registered_by', models.CharField(max_length=100)),
                ('updated_on', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('role', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.Role')),
                ('st_cat', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.StaffCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
