# Generated by Django 2.2.28 on 2024-10-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registered_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
