# Generated by Django 2.2.28 on 2024-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20241006_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
