# Generated by Django 2.2.28 on 2024-10-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20241006_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cgpa_or_percentage',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
