# Generated by Django 2.2.28 on 2024-11-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentsemesterassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester_or_year',
            field=models.IntegerField(default=1),
        ),
    ]
