# Generated by Django 2.2.28 on 2024-11-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_semester_or_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester_or_year',
            field=models.IntegerField(blank=True),
        ),
    ]
