# Generated by Django 2.2.28 on 2024-09-28 14:37

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_abbr', models.CharField(blank=True, max_length=100, null=True)),
                ('authority', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('st_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_cat_name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('dob', models.DateField(default='2002-03-03')),
                ('age', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('dp_image', models.ImageField(blank=True, null=True, upload_to=api.models.dp_upload_to)),
                ('signature', models.ImageField(blank=True, null=True, upload_to=api.models.signature_upload_to)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('is_password_renew', models.BooleanField(default=False)),
                ('renew_password', models.CharField(default='No', max_length=200)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_login', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Department')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Role')),
                ('st_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.StaffCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
