# Generated by Django 2.2.28 on 2024-09-19 17:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.dp_upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.signature_upload_to),
        ),
    ]
