# Generated by Django 2.2.28 on 2024-09-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240926_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default='2002/03/10'),
        ),
    ]
