# Generated by Django 2.2.28 on 2024-10-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20241006_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
