# Generated by Django 2.2.28 on 2024-09-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default='2002-10-10'),
        ),
    ]
