# Generated by Django 2.2.28 on 2024-10-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20241019_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='HOD',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
