# Generated by Django 2.2.28 on 2024-10-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20241030_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
