# Generated by Django 2.2.28 on 2024-12-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20241209_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='HOD',
            field=models.CharField(max_length=250),
        ),
    ]
