# Generated by Django 2.2.28 on 2024-10-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20241019_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
                ('subject_T', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_T_Teacher', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_P', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_P_Teacher', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
