# Generated by Django 2.2.28 on 2024-10-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_auto_20241019_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
