# Generated by Django 2.2.28 on 2024-10-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_type', models.CharField(blank=True, max_length=10, null=True)),
                ('text_book_1', models.CharField(blank=True, max_length=50, null=True)),
                ('text_book_2', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_book_1', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_book_2', models.CharField(blank=True, max_length=50, null=True)),
                ('full_mark', models.IntegerField(blank=True, null=True)),
                ('pass_mark', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
