# Generated by Django 2.2.28 on 2024-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='full_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pass_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(default='P', max_length=10),
        ),
    ]
