# Generated by Django 2.2.28 on 2024-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0009_auto_20241023_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(max_length=10),
        ),
    ]
