# Generated by Django 2.2.28 on 2024-10-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0011_auto_20241024_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
