# Generated by Django 2.2.28 on 2024-10-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0012_auto_20241031_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=50),
        ),
    ]
