# Generated by Django 2.2.28 on 2024-12-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0013_auto_20241031_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
