# Generated by Django 2.2.28 on 2024-11-18 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exam_type', models.CharField(max_length=20)),
                ('exam_date', models.DateField()),
                ('exam_duration', models.FloatField()),
                ('marks_for_correct_ans', models.FloatField()),
                ('is_negative_marking', models.BooleanField()),
                ('negative_mark_per_qn', models.IntegerField(default=0)),
                ('exam_for', models.PositiveSmallIntegerField()),
                ('exam_year', models.IntegerField()),
                ('exam_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
