# Generated by Django 2.2.28 on 2024-12-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20241118_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='batch',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
