# Generated by Django 2.2.28 on 2024-11-07 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('complex', 'Complex')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='faculty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='learning_level',
            field=models.CharField(blank=True, choices=[('remembering', 'Remembering'), ('application', 'Application'), ('evaluation', 'Evaluation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='qn_area',
            field=models.CharField(blank=True, choices=[('short', 'Short Answer'), ('medium', 'Medium Answer'), ('long', 'Long Answer'), ('mcq', 'Multiple Choice Question')], max_length=10),
        ),
    ]
