# Generated by Django 2.2.28 on 2024-11-07 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20241107_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
