# Generated by Django 2.2.28 on 2024-11-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20241107_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_required',
            field=models.IntegerField(help_text='Time required to solve the question'),
        ),
    ]
