# Generated by Django 2.2.28 on 2024-11-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20241107_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
