# Generated by Django 2.2.28 on 2024-11-15 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0006_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qn_title', models.TextField()),
                ('qn_area', models.TextField(blank=True)),
                ('qn_type', models.CharField(max_length=250)),
                ('option_1', models.CharField(blank=True, max_length=200, null=True)),
                ('option_2', models.CharField(blank=True, max_length=200, null=True)),
                ('option_3', models.CharField(blank=True, max_length=200, null=True)),
                ('option_4', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_ans', models.CharField(blank=True, help_text='Specify the correct answer if question type is MCQ', max_length=20, null=True)),
                ('subject', models.CharField(max_length=50)),
                ('learning_level', models.CharField(blank=True, max_length=20)),
                ('difficulty_level', models.CharField(blank=True, max_length=20)),
                ('time_required', models.IntegerField(help_text='Time required to solve the question')),
                ('verification_status', models.CharField(default='not_verified', max_length=15)),
                ('status', models.CharField(default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_uploaded', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
