# Generated by Django 2.2.28 on 2024-11-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qn_title',
            field=models.CharField(max_length=100),
        ),
    ]
